In [1]:
"""Keras is the high-level API of the TensorFlow platform"""

'Keras is the high-level API of the TensorFlow platform'

In [2]:
import tensorflow as tf
import keras
from keras import layers

/Users/ravi_medabalimi/venv-metal/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


### Sequential model 
A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor.

In [3]:
# Creating sequence model

model = keras.Sequential(
    [
        layers.Dense(5, activation = 'relu'),
        layers.Dense(3, activation = 'relu'),
        layers.Dense(1, activation = 'relu')
    ]
)

x = tf.ones((3,5))
y = model(x)
y

2025-05-24 23:59:29.348382: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-05-24 23:59:29.348403: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-05-24 23:59:29.348414: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2025-05-24 23:59:29.348429: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2025-05-24 23:59:29.348441: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>

In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (3, 5)                 │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (3, 3)                 │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (3, 1)                 │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 52 (208.00 B)

 Trainable params: 52 (208.00 B)

 Non-trainable params: 0 (0.00 B)

In [5]:
for parms in model.trainable_variables:
    print(parms)

<Variable path=sequential/dense/kernel, shape=(5, 5), dtype=float32, value=[[-5.3763390e-05 -7.5956738e-01 -6.9618344e-02  3.6455321e-01
   6.6648757e-01]
 [ 6.1640882e-01 -3.6880466e-01 -3.8592285e-01 -3.7064758e-01
  -1.3786232e-01]
 [ 5.4622638e-01  3.2789183e-01 -1.4200687e-01 -5.4972875e-01
   5.6371999e-01]
 [-6.7578739e-01 -6.1082917e-01  1.0039127e-01 -4.9033734e-01
   1.7649901e-01]
 [ 4.7802687e-02 -5.5015188e-01 -4.7143996e-01 -2.3244989e-01
   3.4596491e-01]]>
<Variable path=sequential/dense/bias, shape=(5,), dtype=float32, value=[0. 0. 0. 0. 0.]>
<Variable path=sequential/dense_1/kernel, shape=(5, 3), dtype=float32, value=[[ 0.662059    0.7449818  -0.353468  ]
 [ 0.1696915   0.42026216  0.7732224 ]
 [-0.61005473 -0.07006532  0.11189067]
 [ 0.48632675  0.38018996  0.8113323 ]
 [ 0.02097595  0.27314323 -0.31452817]]>
<Variable path=sequential/dense_1/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>
<Variable path=sequential/dense_2/kernel, shape=(3, 1), dtype=float32, valu

In [6]:
# Creating sequence model using add() method, assingning name for layers and specifying input shape

model = keras.Sequential(name="seq_model")
model.add(layers.Dense(3, activation='relu', input_shape=(5,), name='layer_1'))
model.add(layers.Dense(3, activation='relu', name='layer_2'))
model.add(layers.Dense(1, activation='relu', name='layer_3'))

model.summary()

/Users/ravi_medabalimi/venv-metal/lib/python3.9/site-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "seq_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer_1 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_2 (Dense)                 │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [7]:
y = model(x)
model.summary()

Model: "seq_model"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ layer_1 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_2 (Dense)                 │ (None, 3)              │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ layer_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

**
When building a new Sequential architecture, it's useful to incrementally stack layers with add() and frequently print model summaries. 

Once a Sequential model has been built, it behaves like a Functional API model. This means that every layer has an input and output attribute.

Once a Sequential model has been built, it behaves like a Functional API model. This means that every layer has an input and output attribute.

In [ ]:
# feature extracts the outputs of all intermediate layers in a Sequential model



feature_extractor = keras.Model(
    inputs = model.inputs,
    outputs = model.get_layer(name='layer_2').output
)

features =