In [6]:
import tensorflow as tf
import numpy as np

### Tensors

 Tensors are multidimensional arrays

In [8]:
x = tf.constant([[1, 2, 4],
                 [3, 5, 6]])

x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [3, 5, 6]])>

In [9]:
print(f"Tensor x \n {x}")
print(f"Tensor x shape :   {x.shape}")
print(f"Tensor x dtype :   {x.dtype}")

Tensor x 
 [[1 2 4]
 [3 5 6]]
Tensor x shape :   (2, 3)
Tensor x dtype :   <dtype: 'int32'>


In [10]:
y = tf.convert_to_tensor(np.array([[1, 0, 1],[1, 1, 1]]))
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 0, 1],
       [1, 1, 1]])>

In [19]:
### Tensor operations

print(f"Transpose of x \n {x @ tf.transpose(x)}")

print(f"Concat x & y \n {tf.concat([x,y], axis=0)}")

print(f"Reduce sum {tf.reduce_sum([1,2,3])}")

Transpose of x 
 [[21 37]
 [37 70]]
Concat x & y 
 [[1 2 4]
 [3 5 6]
 [1 0 1]
 [1 1 1]]
Reduce sun 6
